# IDA: Assignment 2

### Deadline: October 3 (until 23:59)


**Instructions:** All answers should be provided in the notebook and then submitted to Moodle. Name of notebook should be in following format:
 - Name_group_Assignment2.ipynb (ex. Tony_Stark_2009_Assignment1.ipynb). PLEASE, use exactly the **same format.**
 - Try to use fewer cells for compilation (for example, you can use print for several answers, instead of printing each answer on a separate cell)
 - **PLEASE:** submit only one jupyter notebook (no zip or csv files) and with your names as in the instruction. Ohterwise, there will be punishment of 30% from your assignment mark.
 - **IMPORTANT NOTE:** you will get points only for correct answers, not for trials or wrong answers. Your notebook should run when we press **"Restart Kernel"** and then press **"Run All"**. We are going to check answers only after doing that. If your code do not compile and stops at any question, you will get zero for that question.

## Q1 (10%)
Using **list comprehension** create a new list from `list_q1_1` and `list_q1_2`. For the values at the same position (index), you should have sum of elements if element of `list_q1_1` is smaller (strictly) than the element of `list_q1_2`. Otherwise, you should take their difference. 

***Note:*** *in the obtained list all values should be positive.*

In [1]:
list_q1_1 = [41, 21, 96, 34, 65, 46, 79, 73, 49, 85, 63, 51, 93, 84, 29, 62, 95, 39, 72, 66]
print(list_q1_1)

[41, 21, 96, 34, 65, 46, 79, 73, 49, 85, 63, 51, 93, 84, 29, 62, 95, 39, 72, 66]


In [2]:
list_q1_2 = [95, 76, 92, 91, 49, 61, 68, 32, 50, 29, 48, 82, 33, 81, 39, 69, 84, 74, 89, 15]
print(list_q1_2)

[95, 76, 92, 91, 49, 61, 68, 32, 50, 29, 48, 82, 33, 81, 39, 69, 84, 74, 89, 15]


In [3]:
# your code here
import math

new_list = [list_q1_1[i] + list_q1_2[i] if list_q1_1[i] < list_q1_2[i] 
      else list_q1_1[i] - list_q1_2[i] for i in range(len(list_q1_1))]
print(new_list)
                                                                                         


[136, 97, 4, 125, 16, 107, 11, 41, 99, 56, 15, 133, 60, 3, 68, 131, 11, 113, 161, 51]


## Q2 (10%)
Using **list comprehension** on `list_q2_1` and `list_q2_2` create a new list containing value pairs, where one of them is divisible by another, but do not include two equal elements. For example, (13, 91) should be included, but (91,91) should not).

In [4]:
list_q2_1 = [97, 29, 43, 96, 91, 22, 51, 83, 31, 13,
             62, 19, 23, 26, 50, 70, 84, 67, 36, 35]
print(list_q2_1)

[97, 29, 43, 96, 91, 22, 51, 83, 31, 13, 62, 19, 23, 26, 50, 70, 84, 67, 36, 35]


In [5]:
list_q2_2 = [31, 63, 98, 91, 46, 71, 37, 70, 75, 33,
             74, 77, 40, 10, 11, 57, 84, 64, 18, 28]
print(list_q2_2)

[31, 63, 98, 91, 46, 71, 37, 70, 75, 33, 74, 77, 40, 10, 11, 57, 84, 64, 18, 28]


In [6]:
# your code here

new_list = [(m, n) for m in list_q2_1 for n in list_q2_2 if (m % n == 0 and m!=n) or (n % m == 0 and n!=m)]
print(new_list)

[(22, 11), (13, 91), (62, 31), (19, 57), (23, 46), (50, 10), (70, 10), (84, 28), (36, 18), (35, 70)]


## Q3 (10%)
Using **list comprehension** obtain a list of all 2-digits prime numbers (for example, 13, 17, 19...).

***Note:*** *it can be done with one line of code.*

In [7]:
# your code here

prime_numbers = [i for i in range(10 , 100) if i%2!=0 and i%3!=0 and i%5!=0 and i%7!=0]
print(prime_numbers)

[11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]


## Q4 (10%)


Using **list comprehension** create a windowing lists of 3 elements at a time with step 1 for `list_q4`. 

Your result should look as following: [[48, 95, 11], [95, 11, 46], [11, 46, 76],..]

***Note:*** *it can be done with one line of code.*

In [8]:
list_q4 = [48, 95, 11, 46, 76, 75, 35, 78, 81, 58, 
           17, 26, 97, 63, 93, 57, 28, 85, 54, 62]
print(list_q4)

[48, 95, 11, 46, 76, 75, 35, 78, 81, 58, 17, 26, 97, 63, 93, 57, 28, 85, 54, 62]


In [9]:
# your code here

sublists = [list_q4[i: i + 3] for i in range(len(list_q4))]
print(sublists)

[[48, 95, 11], [95, 11, 46], [11, 46, 76], [46, 76, 75], [76, 75, 35], [75, 35, 78], [35, 78, 81], [78, 81, 58], [81, 58, 17], [58, 17, 26], [17, 26, 97], [26, 97, 63], [97, 63, 93], [63, 93, 57], [93, 57, 28], [57, 28, 85], [28, 85, 54], [85, 54, 62], [54, 62], [62]]


## Q5 (10%)
For the string below using **dictionary comprihension** create a dictionary, where key - possible word length, and value - number of words of this length. 

***Note:*** *you should not consider keys which are not appearing in the text.*

In [10]:
string_q5 = "From they fine john he give of rich he. They age and draw mrs like. Improving end distrusts may instantly was household applauded incommode. Why kept very ever home mrs. Considered sympathize ten uncommonly occasional assistance sufficient not. Letter of on become he tended active enable to. Vicinity relation sensible sociable surprise screened no up as.Death weeks early had their and folly timed put. Hearted forbade on an village ye in fifteen. Age attended betrayed her man raptures laughter. Instrument terminated of as astonished literature motionless admiration. The affection are determine how performed intention discourse but. On merits on so valley indeed assure of. Has add particular boisterous uncommonly are. Early wrong as so manor match. Him necessary shameless discovery consulted one but."
print(string_q5)

From they fine john he give of rich he. They age and draw mrs like. Improving end distrusts may instantly was household applauded incommode. Why kept very ever home mrs. Considered sympathize ten uncommonly occasional assistance sufficient not. Letter of on become he tended active enable to. Vicinity relation sensible sociable surprise screened no up as.Death weeks early had their and folly timed put. Hearted forbade on an village ye in fifteen. Age attended betrayed her man raptures laughter. Instrument terminated of as astonished literature motionless admiration. The affection are determine how performed intention discourse but. On merits on so valley indeed assure of. Has add particular boisterous uncommonly are. Early wrong as so manor match. Him necessary shameless discovery consulted one but.


In [11]:
# your code here
my_new_list = string_q5.replace('.', ' ').split()
dictionary = {len(z):len([i for i in my_new_list if len(z) == len(i)]) for z in my_new_list }
print(dictionary)

{4: 13, 2: 22, 3: 26, 9: 15, 10: 15, 6: 9, 8: 10, 5: 10, 7: 4}


## Q6 (10%)
Using numpy create two arbitrary matrices A and B of size 3x3 with only 2-digit numbers. And then apply different matrix operations:
1. addition
2. subtraction
3. pointwise multiplication
4. pointwise division
5. matrix dot product
6. transpose
7. determinant
8. rank
9. inverse

In [12]:
import numpy as np

In [13]:
# your code here
a = np.random.randint(10,100,(3,3))
b = np.random.randint(10,100,(3,3))
print('Addition:\n', np.add(a, b), '\n')
print('Subtraction:\n', np.subtract(a, b), '\n')
print('Pointwise multiplication:\n', np.multiply(a, b), '\n')
print('Pointwise division:\n', np.divide(a, b), '\n')
print('Matrix dot product:\n', np.dot(a, b), '\n')
print('Transpose of matrix a:\n', np.transpose(a), '\n')
print('Transpose of matrix b:\n', np.transpose(b), '\n')
print('Determinant of matrix a:\n', np.linalg.det(a), '\n')
print('Determinant of matrix b:\n', np.linalg.det(b), '\n')
print('Rank of matrix a:\n', np.linalg.matrix_rank(a), '\n')
print('Rank of matrix b:\n', np.linalg.matrix_rank(b), '\n')
print('Inverse of matrix a:\n', np.linalg.inv(a), '\n')
print('Inverse of matrix b:\n', np.linalg.inv(b), '\n')

Addition:
 [[113  93 124]
 [ 96 112 148]
 [121 159  98]] 

Subtraction:
 [[-69  35  30]
 [ -2 -74 -46]
 [-67 -35 -52]] 

Pointwise multiplication:
 [[2002 1856 3619]
 [2303 1767 4947]
 [2538 6014 1725]] 

Pointwise division:
 [[0.24175824 2.20689655 1.63829787]
 [0.95918367 0.20430108 0.5257732 ]
 [0.28723404 0.63917526 0.30666667]] 

Matrix dot product:
 [[12376 14059 13017]
 [10002  8077  7877]
 [ 7657  8780  9008]] 

Transpose of matrix a:
 [[22 47 27]
 [64 19 62]
 [77 51 23]] 

Transpose of matrix b:
 [[91 49 94]
 [29 93 97]
 [47 97 75]] 

Determinant of matrix a:
 143871.00000000015 

Determinant of matrix b:
 -251130.00000000023 

Rank of matrix a:
 3 

Rank of matrix b:
 3 

Inverse of matrix a:
 [[-0.01894058  0.02295112  0.01251816]
 [ 0.0020574  -0.01093341  0.01735583]
 [ 0.01668856  0.00253004 -0.01800224]] 

Inverse of matrix b:
 [[ 0.00969219 -0.00949309  0.00620396]
 [-0.02167403 -0.00958468  0.02597858]
 [ 0.0158842   0.02429419 -0.02804125]] 



## Q7 (10%)
For the list below obtain numpy array and then do the following steps:
1. Find all indexes for values between 40 and 60 (both included).
2. Find all values between 40 and 60 (both included).
3. Find all numbers divisible by 3 or 5 or 7.
4. Find all prime numbers in this array (you may use list obtained in Q3).

In [14]:
list_q7 = [53, 58, 93, 96, 40, 97, 95, 24, 27, 61, 
           15, 25, 47, 22, 45, 50, 99, 37, 13, 17, 
           90, 13, 23, 54, 80, 83, 98, 14, 70, 30]
print(list_q7)

[53, 58, 93, 96, 40, 97, 95, 24, 27, 61, 15, 25, 47, 22, 45, 50, 99, 37, 13, 17, 90, 13, 23, 54, 80, 83, 98, 14, 70, 30]


In [15]:
# your code here
a = np.array(list_q7)
print('All indexes for values between 40 and 60:', np.where((a>39) & (a<61)))
print('All values between 40 and 60:', a[np.where ((a>39) & (a<61))])
print('All numbers divisible by 3 or 5 or 7:', a[np.where (((a % 3 == 0) | (a % 5 == 0) | (a % 7 == 0)))])
print('All prime numbers in this array:', a[np.where (((a % 2 != 0) & (a % 3 != 0) & (a % 5 != 0)) & (a % 7 != 0))])

All indexes for values between 40 and 60: (array([ 0,  1,  4, 12, 14, 15, 23], dtype=int64),)
All values between 40 and 60: [53 58 40 47 45 50 54]
All numbers divisible by 3 or 5 or 7: [93 96 40 95 24 27 15 25 45 50 99 90 54 80 98 14 70 30]
All prime numbers in this array: [53 97 61 47 37 13 17 13 23 83]


## Q8 (10%)
Do the following tasks:
1. Create an array of all 3-digit numbers divisible by 33. 
2. Create an array of 19 elements betweem 10 and 100.
3. Create an array of size 20 with random 2-digit values. Replace all numbers divisible by 3 to 'abc'.
4. Create an array of size 20 with random 2-digit values. Find 3 smallest and 3 largest elements. 

In [16]:
# your code here
my_array = np.arange(100,1000)

new_array = my_array[np.where(my_array % 33 == 0)]
print('Array of all 3-digit numbers divisible by 33:\n', new_array, '\n')

my_array1 = np.random.randint(10,100,19)
print('Array of 19 elements betweem 10 and 100:\n', my_array1, '\n')

my_array2 = np.random.randint(10,100,20)
my_replace = np.where(my_array2 % 3 == 0, 'abc', my_array2)
print("Array of size 20 with random 2-digit values, all numbers divisible by 3 = 'abc'\n",my_replace, '\n')

my_array3 = np.random.randint(10,100,20)
print('3 smallest:', my_array3[np.argsort(-my_array3)[-3:]], '\n3 largest:', my_array3[np.argsort(my_array3)[-3:]])

Array of all 3-digit numbers divisible by 33:
 [132 165 198 231 264 297 330 363 396 429 462 495 528 561 594 627 660 693
 726 759 792 825 858 891 924 957 990] 

Array of 19 elements betweem 10 and 100:
 [66 95 75 23 27 23 62 90 37 76 46 76 17 45 41 22 76 97 61] 

Array of size 20 with random 2-digit values, all numbers divisible by 3 = 'abc'
 ['95' 'abc' '53' 'abc' '59' 'abc' '35' '86' 'abc' '20' '76' '47' '52' '23'
 '53' '89' '71' '56' '59' '20'] 

3 smallest: [30 26 18] 
3 largest: [95 98 98]


## Q9 (10%)
Create a matrix of size 4x4 with random 2-digit numbers. Do the following tasks:
1. Find mean along rows and mean along columns.
2. Find max along rows and max along columns.
3. Find indexes of min and max values.
4. Iteratre over matrix, and print its index as (i,j) and corresponding value. For example, Index: (1,1), Value: 50.

In [17]:
# your code here
my_matrix = np.random.randint(10,100,(4,4))

print('Mean along rows:', np.mean(my_matrix,axis=1), '\nMean along columns:', np.mean(my_matrix,axis=0))
print('\nMax along rows:', np.max(my_matrix,axis=1), '\nMin along columns:', np.min(my_matrix,axis=0))
print('\nMax indexes along rows:', np.argmax(my_matrix,axis=1), '\nMin indexes along columns:', np.argmin(my_matrix,axis=0))
print('\nIterate over matrix:')
for index, value in np.ndenumerate(my_matrix):
    print('Index:', index,'Value:', value)

Mean along rows: [49.75 90.5  65.5  50.  ] 
Mean along columns: [61.   64.5  73.   57.25]

Max along rows: [63 98 97 81] 
Min along columns: [26 12 40 25]

Max indexes along rows: [1 0 1 2] 
Min indexes along columns: [3 3 0 2]

Iterate over matrix:
Index: (0, 0) Value: 55
Index: (0, 1) Value: 63
Index: (0, 2) Value: 40
Index: (0, 3) Value: 41
Index: (1, 0) Value: 98
Index: (1, 1) Value: 86
Index: (1, 2) Value: 96
Index: (1, 3) Value: 82
Index: (2, 0) Value: 65
Index: (2, 1) Value: 97
Index: (2, 2) Value: 75
Index: (2, 3) Value: 25
Index: (3, 0) Value: 26
Index: (3, 1) Value: 12
Index: (3, 2) Value: 81
Index: (3, 3) Value: 81


## Q10 (10%)
Create a matrix of size 5x5 with random 2-digit numbers. Do the following tasks:
1. Reverse both along rows and columns.
2. Sort along rows in descending order.
3. Sort along columns in descending order.
4. Sort all 25 elements in descending order, i.e. at index (1,1) you should have the largest element, and at index (5,5) the smallest element. 

In [18]:
# your code here
my_matrix1 = np.random.randint(10,100,(5,5))

print('Reverse both along rows and columns:\n', my_matrix1[::-1,::-1])
print('\nSort along rows in descending order:\n', np.flip(np.sort(my_matrix1,axis=1)))
print('\nSort along columns in descending order:\n', np.flip(np.sort(my_matrix1,axis=0)))
print('\nAll 25 elements in descending order:\n', np.flip(np.sort((np.sort(my_matrix1,axis=1)),axis=0)))


Reverse both along rows and columns:
 [[63 29 76 24 10]
 [80 94 69 99 33]
 [24 62 34 70 70]
 [91 95 14 67 23]
 [49 37 63 83 11]]

Sort along rows in descending order:
 [[76 63 29 24 10]
 [99 94 80 69 33]
 [70 70 62 34 24]
 [95 91 67 23 14]
 [83 63 49 37 11]]

Sort along columns in descending order:
 [[91 95 76 99 70]
 [80 94 69 83 33]
 [63 62 63 70 23]
 [49 37 34 67 11]
 [24 29 14 24 10]]

All 25 elements in descending order:
 [[99 94 80 69 33]
 [95 91 67 37 24]
 [83 70 62 34 14]
 [76 63 49 24 11]
 [70 63 29 23 10]]


---

### Evaluation (Keep it!)

| Question | Mark     | Comment   
|:-------:|:--------:|:----------------------
| 1       |   10/10    |     
| 2       |   10/10     | 
| 3       |   10/10     | 
| 4       |   10/10     | 
| 5       |   10/10    |     
| 6       |   10/10     | 
| 7       |   10/10     | 
| 8       |   10/10     | 
| 9       |   10/10     | 
| 10       |   10/10     | 
|**Total**|**100/100**  | 
